spring:
  application:
    name: spring-cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: OrderService
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service(?<remains>/?.*), $\{remains}
        - id: ProductService
          uri: lb://product-service
          predicates:
            - Path=/product-service/**
          filters:
            - RewritePath=/product-service(?<remains>/?.*), $\{remains}
        - id: ShoppingCartCommandService
          uri: lb://shopping-cart-command-service
          predicates:
            - Path=/shopping-cart-command-service/**
          filters:
            - RewritePath=/shopping-cart-command-service(?<remains>/?.*), $\{remains}
        - id: ShoppingCartQueryService
          uri: lb://shopping-cart-query-service
          predicates:
            - Path=/shopping-cart-query-service/**
          filters:
            - RewritePath=/shopping-cart-query-service(?<remains>/?.*), $\{remains}
  zipkin:
    base-url: http://localhost:9411/

server:
  port: 8079

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
