server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SujanKoju/config-files.git
          default-label: master
          clone-on-start: true
encrypt:
  key: sakjdslakjd1264564213145{}asdkj??123



